---
- name: Playbook to backup configs on Cisco Routers
  connection: local
  hosts: device_roles_TS32_DLSW , device_roles_TS14_DL_SW , device_roles_TS11_DL_SW , device_roles_TS13_DL_SW
  gather_facts: False

  vars:
    cli:
      username: admin
      password: cisco

  tasks:
    - name: Show running config on device
      ios_command:
        provider: "{{ cli }}"
        commands:
          - show run
      register: config

    - name: Save output to backups folder
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}-config.txt"
