---
- name: create config using netbox
  connection: local
  hosts: device_roles_router
  gather_facts: False

  tasks:
   - name: "Generate configs using data obtained from netbox"
     template:
       src: "./templets/config_templete.j2"
       dest: "./outpu/{{ inventory_hostname }}.cfg"
       lstrip_blocks: yes
