---

- name: Update apt packages
  apt:
    update_cache: yes
  become: yes
  tags:
    - system

- name: Set time zone to Europe/London
  timezone:
    name: Europe/London
  become: yes
  tags:
    - system
